#!/bin/bash -l
#SBATCH --account=uzh8
#SBATCH --job-name="ns_hpc_sheet2_mpi"
#SBATCH --mail-type=ALL
#SBATCH --mail-user=nora.salgo@uzh.ch
#SBATCH --time=00:05:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=36
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
#SBATCH --constraint=mc
#SBATCH --hint=nomultithread

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun cpi_mpi
