#!/bin/bash -l
#SBATCH --account=uzh8
#SBATCH --job-name="ns_hpc_sheet2_mpi"
#SBATCH --mail-type=ALL
#SBATCH --mail-user=nora.salgo@uzh.ch
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=36
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH -e errors.log
#SBATCH -o output.log

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun cpi_omp
